version: '3.4'

services:
  app: &app
    image: node:12
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules

  runner:
    <<: *app
    command: /bin/bash
    stdin_open: true
    tty: true

  server:
    <<: *app
    command: bash -c "yarn cache clean && yarn install && yarn start"
    ports:
      - "8080:8080"

volumes:
  node_modules:
